version: '3.7'

services:
  mysql:
    image: mysql
    ports:
      - '23306:3306'
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_USER: cookbook_user
      MYSQL_PASSWORD: cookbook_password
      MYSQL_DATABASE: cookbook_db