version: '3.7'

services:

  db:
    image: mariadb
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_USER: cookbook_user
      MYSQL_PASSWORD: cookbook_password
      MYSQL_DATABASE: cookbook_db
    ports:
      - 23306:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080