version: '3.7'

services:
  mysql:
    image: mysql
    ports:
      - '23306:3306'
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_USER: cookbook_user
      MYSQL_PASSWORD: cookbook_password
      MYSQL_DATABASE: cookbook_db

  rabbit-mq:
    image: rabbitmq:3-management
    ports:
      - 15672:15672
      - 5672:5672
    hostname: my-rabbit
    environment:
      RABBITMQ_DEFAULT_USER: rabbit_user
      RABBITMQ_DEFAULT_PASS: rabbit_password